post http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRFTEVUWSIsImlkIjoiNWZlZTA4NTQxODg5YzQzMDdjNTRhNDk0IiwiaWF0IjoxNjA5NDM5OTUzfQ.E1tGRlvZR2szMUB4wj9vDQae7oqLQM5PZVhlBlZz0_s

{
"title": "Going TO BE DELETED MOFOFOF",
"author": "USER CREATION another note",
"url": "AUTH_jjdjdjdjdjg.cwwwom",
"likes": 3
}
