post http://localhost:3001/api/blogs/
Content-Type: application/json

{
"title": "California love",
"author": "another note",
"url": "blg@blog.cwwwom",
"likes": 2,
"userId": "5fdc129fa9d61a55d8c9454b"
}
